version: '3.8'
services: 
  db:
    image: mysql:latest
    env_file: 
      - .env
    environment:
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASS
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    restart: always
    
  back:
    build: ./back
    depends_on:
      - db
    restart: always
    ports:
      - "3001:3001"
    env_file: 
      - .env

  front:
    build: ./front
    depends_on:
      - db
      - back
    restart: always
    env_file: 
      - .env
    ports:
      - "3000:80"
      
volumes:
  db: